#include "codigos.h"

/* BORRAR CUANDO YA ESTÉN IMPLEMENTADOS LOS FIRST!!!!!!! */
#include <limits.h>
#define PLACEHOLDER LLONG_MAX
/* */

#define F_UNIDAD_TRADUCCION (F_DECLARACIONES)
#define F_DECLARACIONES (F_ESPECIFICADOR_TIPO)
#define F_ESPECIFICADOR_TIPO (CVOID | CCHAR | CINT | CFLOAT)
#define F_ESPECIFICADOR_DECLARACION (F_DEFINICION_FUNCION | F_DECLARACION_VARIABLE)
#define F_DEFINICION_FUNCION (CPAR_ABR)
#define F_DECLARACION_VARIABLE (F_DECLARADOR_INIT | CCOMA | CPYCOMA)
#define F_LISTA_DECLARACIONES_PARAM (F_DECLARACION_PARAMETRO)
#define F_DECLARACION_PARAMETRO (F_ESPECIFICADOR_TIPO)
#define F_DECLARADOR_INIT (CASIGNAC | CCOR_ABR)
#define F_LISTA_DECLARACIONES_INIT (CIDENT)
#define F_LISTA_INICIALIZADORES (F_CONSTANTE)
#define F_LISTA_DECLARACIONES (F_DECLARACION)
#define F_DECLARACION (F_ESPECIFICADOR_TIPO)
#define F_PROPOSICION_COMPUESTA (CLLA_ABR)
#define F_PROPOSICION_ITERACION (CWHILE)
#define F_PROPOSICION_SELECCION (CIF)
#define F_PROPOSICION_E_S (CIN | COUT)
#define F_PROPOSICION_RETORNO (CRETURN)
#define F_PROPOSICION_EXPRESION (F_EXPRESION | CPYCOMA)
#define F_PROPOSICION (F_PROPOSICION_COMPUESTA | F_PROPOSICION_ITERACION | F_PROPOSICION_SELECCION | F_PROPOSICION_E_S | F_PROPOSICION_RETORNO | F_PROPOSICION_EXPRESION)
#define F_LISTA_PROPOSICIONES (F_PROPOSICION)
#define F_RELACION (CDISTINTO | CIGUAL | CMENOR | CMEIG | CMAIG | CMAYOR)
#define F_VARIABLE (CIDENT)
#define F_LLAMADA_FUNCION (CIDENT)
#define F_CONSTANTE (CCONS_ENT | CCONS_FLO | CCONS_CAR)
#define F_FACTOR (F_VARIABLE | F_CONSTANTE | CNEG | CPAR_ABR | F_LLAMADA_FUNCION | CCONS_STR)
#define F_TERMINO (F_FACTOR)
#define F_EXPRESION_SIMPLE ( CMAS | CMENOS | F_TERMINO)
#define F_EXPRESION ( F_EXPRESION_SIMPLE )
#define F_LISTA_EXPRESIONES ( F_EXPRESION )

#define F_RESTO_OPCIONAL ( CCOR_ABR )
#define F_OPERADOR_OPCIONAL ( CMAS | CMENOS )
#define F_RESTO_EXPRESION (CASIGNAC | F_RELACION)
#define F_RESTO_EXPRESION_SIMPLE (F_OPERADOR_OPCIONAL | COR)
#define F_RESTO_TERMINO (CMULT | CDIV | CAND)
#define F_RESTO_LISTA_EXPRESIONES ( CCOMA )
#define F_OPERADOR PLACEHOLDER
#define F_OPERADOR_MUL PLACEHOLDER

#define F_ELSE_OPCIONAL (CELSE)
#define F_RESTO_PROP_IN (CSHR)
#define F_RESTO_PROP_OUT (CSHL)

#define F_RESTO_LISTA_DECLARACIONES_PARAM (CCOMA)
#define F_RESTO_LISTA_DECLARACIONES_INIT (CCOMA)
#define F_RESTO_LISTA_INICIALIZADORES (CCOMA)
#define F_OPREF_OPCIONAL (CAMPER)
#define F_ARREGLO_OPCIONAL (CCOR_ABR)
#define F_LIMITE_OPCIONAL (CCONS_ENT | CCONS_FLO | CCONS_CAR)
#define F_LISTA_OPCIONAL (CASIGNAC)
