#include "codigos.h"

/* BORRAR CUANDO YA ESTÉN IMPLEMENTADOS LOS FIRST!!!!!!! */
#include <limits.h>
#define PLACEHOLDER LLONG_MAX
/* */

#define F_UNIDAD_TRADUCCION PLACEHOLDER
#define F_DECLARACIONES PLACEHOLDER
#define F_ESPECIFICADOR_TIPO (CVOID | CCHAR | CINT | CFLOAT)
#define F_ESPECIFICADOR_DECLARACION PLACEHOLDER
#define F_DEFINICION_FUNCION PLACEHOLDER
#define F_DECLARACION_VARIABLE PLACEHOLDER
#define F_LISTA_DECLARACIONES_PARAM PLACEHOLDER
#define F_DECLARACION_PARAMETRO PLACEHOLDER
#define F_DECLARADOR_INIT PLACEHOLDER
#define F_LISTA_DECLARACIONES_INIT PLACEHOLDER
#define F_LISTA_INICIALIZADORES PLACEHOLDER
#define F_LISTA_PROPOSICIONES PLACEHOLDER
#define F_LISTA_DECLARACIONES PLACEHOLDER
#define F_DECLARACION PLACEHOLDER
#define F_PROPOSICION PLACEHOLDER
#define F_PROPOSICION_EXPRESION PLACEHOLDER
#define F_PROPOSICION_COMPUESTA PLACEHOLDER
#define F_PROPOSICION_SELECCION PLACEHOLDER
#define F_PROPOSICION_ITERACION PLACEHOLDER
#define F_PROPOSICION_E_S PLACEHOLDER
#define F_PROPOSICION_RETORNO PLACEHOLDER
#define F_EXPRESION PLACEHOLDER
#define F_EXPRESION_SIMPLE PLACEHOLDER
#define F_RELACION (CDISTINTO, CIGUAL, CMENOR, CMEIG, CMAIG, CMAYOR)
#define F_TERMINO PLACEHOLDER
#define F_FACTOR PLACEHOLDER
#define F_VARIABLE (CIDENT)
#define F_LLAMADA_FUNCION PLACEHOLDER
#define F_LISTA_EXPRESIONES PLACEHOLDER
#define F_CONSTANTE (CCONS_ENT | CCONS_FLO | CCONS_CAR)

#define F_RESTO_EXPRESION PLACEHOLDER
#define F_RESTO_EXPRESION_SIMPLE PLACEHOLDER
#define F_RESTO_TERMINO PLACEHOLDER
#define F_RESTO_OPCIONAL PLACEHOLDER
#define F_RESTO_LISTA_EXPRESIONES PLACEHOLDER
#define F_OPERADOR_OPCIONAL PLACEHOLDER
#define F_OPERADOR PLACEHOLDER
#define F_OPERADOR_MUL PLACEHOLDER

#define F_ELSE_OPCIONAL PLACEHOLDER
#define F_RESTO_PROP_IN PLACEHOLDER
#define F_RESTO_PROP_OUT PLACEHOLDER

#define F_RESTO_LISTA_DECLARACIONES_PARAM PLACEHOLDER
#define F_RESTO_LISTA_DECLARACIONES_INIT PLACEHOLDER
#define F_RESTO_LISTA_INICIALIZADORES PLACEHOLDER
#define F_OPREF_OPCIONAL PLACEHOLDER
#define F_ARREGLO_OPCIONAL PLACEHOLDER
#define F_LIMITE_OPCIONAL PLACEHOLDER
#define F_LISTA_OPCIONAL PLACEHOLDER
