#include "codigos.h"

/* BORRAR CUANDO YA ESTÉN IMPLEMENTADOS LOS FIRST!!!!!!! */
#include <limits.h>
#define PLACEHOLDER LLONG_MAX
/* */

#define F_UNIDAD_TRADUCCION PLACEHOLDER
#define F_DECLARACIONES PLACEHOLDER
#define F_ESPECIFICADOR_TIPO (CVOID | CCHAR | CINT | CFLOAT)
#define F_ESPECIFICADOR_DECLARACION PLACEHOLDER
#define F_DEFINICION_FUNCION PLACEHOLDER
#define F_DECLARACION_VARIABLE PLACEHOLDER
#define F_LISTA_DECLARACIONES_PARAM PLACEHOLDER
#define F_DECLARACION_PARAMETRO PLACEHOLDER
#define F_DECLARADOR_INIT PLACEHOLDER
#define F_LISTA_DECLARACIONES_INIT PLACEHOLDER
#define F_LISTA_INICIALIZADORES PLACEHOLDER
#define F_LISTA_DECLARACIONES PLACEHOLDER
#define F_DECLARACION PLACEHOLDER
#define F_PROPOSICION_COMPUESTA (CLLA_ABR)
#define F_PROPOSICION_ITERACION (CWHILE)
#define F_PROPOSICION_SELECCION (CIF)
#define F_PROPOSICION_E_S (CIN | COUT)
#define F_PROPOSICION_RETORNO (CRETURN)
#define F_PROPOSICION_EXPRESION (CMAS | CMENOS | CIDENT | CPAR_ABR | CNEG | CCONS_ENT | CCONS_FLO | CCONS_CAR | CCONS_STR | CPYCOMA)
#define F_PROPOSICION (CLLA_ABR | CWHILE | CIF | CIN | COUT | CRETURN | CMAS | CMENOS | CIDENT | CPAR_ABR | CNEG | CCONS_ENT | CCONS_FLO | CCONS_CAR | CCONS_STR | CPYCOMA)
#define F_LISTA_PROPOSICIONES (CLLA_ABR | CWHILE | CIF | CIN | COUT | CRETURN | CMAS | CMENOS | CIDENT | CPAR_ABR | CNEG | CCONS_ENT | CCONS_FLO | CCONS_CAR | CCONS_STR | CPYCOMA)
#define F_RELACION (CDISTINTO | CIGUAL | CMENOR | CMEIG | CMAIG | CMAYOR)
#define F_VARIABLE (CIDENT)
#define F_LLAMADA_FUNCION (CIDENT)
#define F_CONSTANTE (CCONS_ENT | CCONS_FLO | CCONS_CAR)
#define F_FACTOR (F_VARIABLE | F_CONSTANTE | CNEG | CPAR_ABR | F_LLAMADA_FUNCION | CCONS_STR)
#define F_TERMINO (F_FACTOR)
#define F_EXPRESION_SIMPLE ( CMAS | CMENOS | F_TERMINO)
#define F_EXPRESION ( F_EXPRESION_SIMPLE )
#define F_LISTA_EXPRESIONES ( F_EXPRESION )

#define F_RESTO_OPCIONAL ( CCOR_ABR )
#define F_OPERADOR_OPCIONAL ( CMAS | CMENOS )
#define F_RESTO_EXPRESION (CASIGNAC | F_RELACION)
#define F_RESTO_EXPRESION_SIMPLE (F_OPERADOR_OPCIONAL | COR)
#define F_RESTO_TERMINO (CMULT | CDIV | CAND)
#define F_RESTO_LISTA_EXPRESIONES ( CCOMA )
#define F_OPERADOR PLACEHOLDER
#define F_OPERADOR_MUL PLACEHOLDER

#define F_ELSE_OPCIONAL (CELSE)
#define F_RESTO_PROP_IN (CSHR)
#define F_RESTO_PROP_OUT (CSHL)

#define F_RESTO_LISTA_DECLARACIONES_PARAM PLACEHOLDER
#define F_RESTO_LISTA_DECLARACIONES_INIT PLACEHOLDER
#define F_RESTO_LISTA_INICIALIZADORES PLACEHOLDER
#define F_OPREF_OPCIONAL PLACEHOLDER
#define F_ARREGLO_OPCIONAL PLACEHOLDER
#define F_LIMITE_OPCIONAL PLACEHOLDER
#define F_LISTA_OPCIONAL PLACEHOLDER
